### ISSUE TITLE
Plugin updates Q4/2023

### ISSUE THREAD

**Issue by joelabreo227** [rtCamp/search-with-google#19]
- [x] WordPress plugin codebase standards sweep
- [x] PHP 8.2 compatibility sweep
- [x] WPVIP compatibility sweep
- [x] Documentation updates

Before starting the work on this, please add your time estimations for the task and get it approved by your Project Co-ordinator or Project Manager

**Comment by SH4LIN** [comment]
## Task estimation: `~2~3 days`

- Task estimation includes the plugin update along with the QA of plugin.

- Plan of action for this task:

1. I haven't used this plugin so getting familiar with this plugin to understand the plugin to update it.
2. Fix the WP Coding standard issues.
3. Update the PHP code that uses new PHP syntax for example add the type declarations for the function parameter and return types.
4. Make the plugin VIP compatible.
